# Generated by Django 3.0.2 on 2020-02-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='phone_book_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook_name', models.CharField(max_length=100)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='phone_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('group', models.ManyToManyField(blank=True, null=True, to='sms_sender.group_name')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_sender.phone_book_list')),
            ],
        ),
        migrations.AddField(
            model_name='group_name',
            name='phonebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_sender.phone_book_list'),
        ),
    ]
