# Generated by Django 3.0.2 on 2020-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0003_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_info',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
