# Generated by Django 3.0.2 on 2020-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0004_auto_20200224_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device_info',
            name='id_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device_info',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
