# Generated by Django 3.0.2 on 2020-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0005_auto_20200224_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sms_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
