# Generated by Django 3.0.2 on 2020-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0006_sms_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
