# Generated by Django 3.0.2 on 2020-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0009_date_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='readornot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
